// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xkvmdrncktxqreskzgug.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inhrdm1kcm5ja3R4cXJlc2t6Z3VnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ0NTc5NDIsImV4cCI6MjA2MDAzMzk0Mn0.F_ajTquZqWYHCF_EQqoM3vHiX53jcWtG4QqPgC_NxiI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);